# Bugs and errors

> Debugging is twice as hard as writing the code in the first place. Therefore, if you write the code as cleverly as possible, you are, by definition, not smart enough to debug it.

**Bugs**

- Flaws in computer programs are usually called *bugs*
- The process of finding mistakes (bugs) in programs is called *debugging*

**Language**

- Many mistakes could be pointed out to us automatically by the computer, if it knew enough about what we're trying to do
- But here JS's looseness is a hindrance
- Its concept of bindings and properties is vague enough that it will rarely catch typos before actually running the program
- And even then, it allows you to do some clearly nonsensical things without complaint, such as computing `true * "monkey"`

**Strict mode**

- JS can be made a *little* stricter by enabling *strict mode*
- This is done by putting the string `"use strict"` at the top of a file or a function body:

```
function canYouSpotTheProblem() {
	"use strict";
	for (i = 0; i < 10; i++) {
		console.log(i);
	}
}

canYouSpotTheProblem();
// Uncaught ReferenceError: i is not defined
```

- Normally, when you forget to put `let` in front of your binding, as with `i` in the example, JS quietly creates a global binding and uses that
- In strict mode, an error is reported instead
- Another change in strict mode is that the `this` binding holds the value `undefined` in functions that are not called as methods
- When making such a call outside of strict mode, `this` refers to the global scope object, which is an object whose properties are the global bindings
- So if you accidentally call a method or constructor incorrectly in strict mode, JS will produce an error as soon as it tries to read something from `this`, rather than happily writing to the global scope
- For example, consider the following code, which calls a constructor function without the `new` keyword so that its `this` will *not* refer to a newly constructed object:

```
function Person(name) { this.name = name; }
let tom = Person("Tom");
console.log(name); // Tom
```

- So the bogus call to `Person` succeeded but returned an undefined value and created the global binding `name`
- In strict mode, we are immediately told that something is wrong:

```
"use strict";
function Person(name) { this.name = name; }
let tom = Person("Tom");
// Uncaught TypeError: Cannot set property 'name' of undefined
```

- Strict mode does a few more things:
	- It disallows giving a function multiple parameters with the same name
	- It removes certain problematic language features entirely (such as the `with` statement) etc.
- In short, putting `"use strict"` at the top of your program rarely hurts and might help you spot a problem

**Types**

- Some languages want to know the types of all your bindings and expressions before even running a program
- They will tell you right away when a type is used in an inconsistent way
- JS considers types only when actually running the program, and even there often tries to implicitly convert values to the type it expects, so it's not much help
- Still, types provide a useful framework for talking about programs
	- A lot of mistakes come from being confused about the kind of value that goes into or comes out of a function
	- When the types of a program are known, it is possible for the computer to *check* them for you, pointing out mistakes before the program is run
- There are several JS dialects that add types to the language and check them, the most popular one is called TypeScript

**Testing**

- If the language is not going to do much to help us find mistakes, we'll have to find them the hard way: by running the program and seeing whether it does the right thing
- Doing this by hand, again and again, is a bad idea
- Computers are good at repetitive tasks, and testing is the ideal repetitive task
- Automated testing is the process of writing a program that tests another program
- Writing tests is a bit more work than testing manually, but once you've done it, it takes you only a few seconds to verify that your program still behaves properly in all the situations you wrote tests for
- *Test suites* - a piece of software that help you build and run collections of tests by providing a language suited to expressing tests and by outputting informative information when a test fails

**Debugging**

- Once you notice there is something wrong with your program because it misbehaves or produces errors, the next step is to figure out what the problem is
- Sometimes it is obvious - the error message will point at a specific line of your program, and if you look at the error description and that line of code, you can often see the problem
- But not always: sometimes the line that triggered the problem is simply the first place where a flaky value produced elsewhere gets used in an invalid way
- Consider the following example:

```
function numberToString(n, base = 10) {
	let result = "", sign = "";
	if (n < 0) {
		sign = "-";
		n = -n;
	}
	do {
		result = String(n % base) + result;
		n /= base;
	} while (n > 0);
	return sign + result;
}

console.log(numberToString(13));
// 1.5e-3231.3e-3221.3e-3211.3e-3201.3e-3191.3e-3181.3e-3171.3e...
```

- We know that our program is malfunctioning, and we want to find out why
- *Think.*
- Analyze what is happening and come up with a theory of why it might be happening
- Then, make additional observations to test this theory, or, if you don't yet have a theory, make additional observations to help you come up with one
- Putting a few strategic `console.log` calls into the program is a good way to get additional information about what the program is doing - in this case, we want `n` to take the values `13`, `1`, and then `0` - let's write out its value at the start of the loop:

```
13
1.3
0.13
...
```

- *Right!*
- Dividing 13 by 10 does not produce a whole number
- Instead of `n /= base`, what we actually want is `n = Math.floor(n / base)` so that the number is properly "shifted" to the right
- An alternative to using `console.log` to peek into the program's behavior is to use the *debugger* capabilities of your browser
- Browsers come with the ability to set a *breakpoint* on a specific line of your code
- When the execution of the program reaches a line with a breakpoint, it is paused, and you can inspect the values of bindings at that point
- Another way to set a breakpoint is to include a `debugger` statement in your program
- If the developer tools of your browser are active, the program will pause whenever it reaches such a statement

**Error propagation**

- Unfortunately not all problems can be prevented by the programmer
- If your program communicates with the outside world in any way, it is possible to get malformed input, to become overloaded with work, or to have the network fail
- If you're programming only for yourself, you can afford to just ignore such problems until they occur
- But if you build something that is going to be used by anybody else, you usually want the program to do better than just crash
- Sometimes the right thing to do is take the bad input in stride and continue running
- In other cases, it is better to report to the user what went wrong and then give up
- But in either situation, the program has to actively do something in response to the problem
- Say you have a function `promptNumber` that asks the user for a number and returns it - what should it return if the user inputs "orange"?
- One option is to make it return a special value: common choices for such values are `null`, `undefined`, or `-1`

```
function promptNumber(question) {
	let result = Number(prompt(question));
	if (Number.isNaN(result)) return null;
	else return result;
}

console.log(promptNumber("Pick a number:"));
```

- Now any code that calls `promptNumber` must check whether an actual number was read and, failing that, must somehow recover - maybe by asking again or by filling in a default value
- In many situations, mostly when errors are common and the caller should be explicitly taking them into account, returning a special value is a good way to indicate an error
- It does, however, have its downsides
- What if the function can already return every possible kind of value?
- You'll have to do something like wrap the result in an object to be able to distinguish success from failure
- That can lead to awkward code

**Exceptions**

- When a function cannot proceed normally, what we would *like* to do is just stop what we are doing and immediately jump to a place that knows how to handle the problem
- This is what *exception handling* does
- Exceptions are a mechanism that makes it possible for code that runs into a problem to *raise* (or *throw*) an exception
- Raising one somewhat resembles a super-charged return from a function: it jumps out of not just the current function but also its callers, all the way down to the first call that started the current execution
	- This is called *unwinding the stack*
	- An exception zooms down the stack of function calls, throwing away all the call contexts it encounters
- Once you've caught an exception, you can do something with it to address the problem and then continue to run the program:

```
function promptDirection(question) {
	let result = prompt(question);
	if (result.toLowerCase() == "left") return "L";
	if (result.toLowerCase() == "right") return "R";
	throw new Error("Invalid direction: " + result);
}

function look() {
	if (promptDirection("Which way") == "L") {
		return "A house";
	} else {
		return "Two angry bears";
	}
}

try {
	console.log("You see", look());
} catch (error) {
	console.log("Something went wrong!");
	console.log(error);
}
```

- The `throw` keyword is used to raise an exception
- Catching one is done by wrapping a piece of code in a `try` block, followed by the keyword `catch`
- When the code in the `try` block causes an exception to be raised, the `catch` block is evaluated, with the name in parentheses bound to the exception value
- After the `catch` block finishes, or if the `try` block finishes without problems, the program proceeds beneath the entire `try/catch` statement
- In this case, we used the `Error` constructor to create our exception value
- This is a standard JS constructor that creates an object with a `message` property

**Cleaning up after exceptions**

- The effect of an exception is another kind of control flow
- Every action that might cause an exception, which is pretty much every function call and property access, might cause control to suddenly leave your code
- Here is some really bad banking code:

```
const accounts = {
	a: 100,
	b: 0,
	c: 20
};

function getAccount() {
	let accountName = prompt("Enter an account name:");
	if (!accounts.hasOwnProperty(accountName)) {
		throw new Error(`No such account: ${accountName}`);
	}
	return accountName;
}

function transfer(from, amount) {
	if (accounts[from] < amount) return;
	accounts[from] -= amount;
	accounts[getAccount()] += amount;
}
```

- The `transfer` function transfers a sum of money from a given account to another, asking for the name of the other account in the process
- If given an invalid account name, `getAccount` throws an exception
- But `transfer` *first* removes the money from the account and *then* calls `getAccount` before it adds it to another account
- If it is broken off by an exception at that point, it'll just make the money disappear
- There is another feature that `try` statements have - they may be followed by a `finally` block either instead of or in addition to a `catch` block
- A `finally` block says "no matter what happens, run this code after trying to run the code in the try block"

```
function transfer(from, amount) {
	if (accounts[from] < amount) return;
	let progress = 0;
	try {
		accounts[from] -= amount;
		progress = 1;
		accounts[getAccount()] += amount;
		progress = 2;
	} finally {
		if (progress == 1) {
			accounts[from] += amount;
		}
	}
}
```

- This version of the function tracks its progress, and if, when leaving, it notices that it was aborted at a point where it had created an inconsistent program state, it repairs the damage it did
- Note that even though the `finally` code is run when an exception is thrown in the `try` block, it does not interfere with the exception
- After the `finally` block runs, the stack continues unwinding

**Selective catching**

- When an exception makes it all the way to the bottom of the stack without being caught, it gets handled by the environment
- What this means differs between environments:
	- In browsers, a description of the error typically gets written to the JS console (reachable through the browser's Tools or Developer menu)
	- Node.js aborts the whole process when an unhandled exception occurs
- For programmer mistakes, just letting the error go through is often the best you can do - an unhandled exception is a reasonable way to signal a broken program, and the JS console will, on modern browsers, provide you with some information about which function calls were on the stack when the problem occurred

```
for (;;) {
	try {
		let dir = promtDirection("Where?"); // Typo!
		console.log(`You chose: ${dir}`);
		break;
	} catch (e) {
		console.log("Not a valid direction. Try again.");
	}
}
```

- We misspelled `promptDirection`, which will result in an "undefined variable" error
- Because the `catch` block completely ignores its exception value (`e`), assuming it knows what the problem is, it wrongly treats the binding error as indicating bad input
- So we want to catch a *specific* kind of exception
- We can do this by checking in the `catch` block whether the exception we got is the one we are interested in and rethrowing it otherwise
- We could compare its `message` property against the error message we happen to expect - but that's a shaky way to write code - we'd be using information that's intended for human consumption (the message) to make a programmatic decision
- As soon as someone changes (or translates) the message, the code will stop working
- Rather, let's define a new type of error and use `instanceof` to identify it

```
class InputError extends Error {}

function promptDirection(question) {
	let result = prompt(question);
	if (result.toLowerCase() == "left") return "L";
	if (result.toLowerCase() == "right") return "R";
	throw new InputError("Invalid direction: " + result);
}

for (;;) {
	try {
		let dir = promptDirection("Where?");
		console.log(`You chose: ${dir}`);
		break;
	} catch (e) {
		if (e instanceof InputError) {
			console.log("Not a valid direction. Try again.");
		} else {
			throw e;
		}
	}
}
```

- This will catch only instances of `InputError` and let unrelated exceptions through
- If you reintroduce the typo, the undefined binding error will be properly reported

**Assertions**

- *Assertions* are checks inside a program that verify that something is the way it is supposed to be
- They are used not to handle situations that can come up in normal operation but to find programmer mistakes
- If, for example, `firstElement` is described as a function that should never be called on empty arrays, we might write it like this:

```
function firstElement(array) {
	if (array.length == 0) {
		throw new Error("firstElement called with []");
	}
	return array[0];
}
```

- Now, instead of silently returning undefined (which you get when reading an array property that does not exist), this will loudly blow up your program as soon as you misuse it
- This makes it less likely for such mistakes to go unnoticed and easier to find their cause when they occur
